// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCd5azxskAsJPxzUhYrJKbFe0nO99Kj4_E',
    appId: '1:121769632696:web:994f0ad48371b86107254d',
    messagingSenderId: '121769632696',
    projectId: 'image-54a1e',
    authDomain: 'image-54a1e.firebaseapp.com',
    databaseURL: 'https://image-54a1e-default-rtdb.firebaseio.com',
    storageBucket: 'image-54a1e.appspot.com',
    measurementId: 'G-DXRCVJGZ9H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFHgdJWZQFivawxaxnrhK1LsV2S7SqTdM',
    appId: '1:121769632696:android:c1f2a7cff8abbf4307254d',
    messagingSenderId: '121769632696',
    projectId: 'image-54a1e',
    databaseURL: 'https://image-54a1e-default-rtdb.firebaseio.com',
    storageBucket: 'image-54a1e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCB-Qj6F3PgPukYQ3bNn_iia243f--WTRY',
    appId: '1:121769632696:ios:8210d65d082d9c9a07254d',
    messagingSenderId: '121769632696',
    projectId: 'image-54a1e',
    databaseURL: 'https://image-54a1e-default-rtdb.firebaseio.com',
    storageBucket: 'image-54a1e.appspot.com',
    androidClientId: '121769632696-ckc9o9jknfe886j5q89p1cb64pn4s8n9.apps.googleusercontent.com',
    iosClientId: '121769632696-lb13hpp57aap46f4mkj7uj1oipun6mu1.apps.googleusercontent.com',
    iosBundleId: 'com.example.contest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCB-Qj6F3PgPukYQ3bNn_iia243f--WTRY',
    appId: '1:121769632696:ios:8210d65d082d9c9a07254d',
    messagingSenderId: '121769632696',
    projectId: 'image-54a1e',
    databaseURL: 'https://image-54a1e-default-rtdb.firebaseio.com',
    storageBucket: 'image-54a1e.appspot.com',
    androidClientId: '121769632696-ckc9o9jknfe886j5q89p1cb64pn4s8n9.apps.googleusercontent.com',
    iosClientId: '121769632696-lb13hpp57aap46f4mkj7uj1oipun6mu1.apps.googleusercontent.com',
    iosBundleId: 'com.example.contest',
  );
}
